# Generated by Django 3.0.5 on 2021-02-11 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=500)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(max_length=150)),
                ('cdesc', models.CharField(max_length=1000)),
                ('cdoclink', models.URLField(max_length=300)),
                ('ciname', models.CharField(max_length=150)),
                ('cidesc', models.CharField(max_length=1000)),
                ('cilink', models.URLField(max_length=300)),
                ('csdate', models.CharField(max_length=100)),
                ('cedate', models.CharField(max_length=100)),
                ('ctime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('qual', models.CharField(max_length=1000)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoname', models.CharField(max_length=150)),
                ('ngodetails', models.CharField(max_length=1000)),
                ('ntitle', models.CharField(max_length=150)),
                ('ndesc', models.CharField(max_length=1000)),
                ('ndoclink', models.URLField(max_length=300)),
                ('niname', models.CharField(max_length=150)),
                ('nidesc', models.CharField(max_length=1000)),
                ('nilink', models.URLField(max_length=300)),
                ('nsdate', models.CharField(max_length=100)),
                ('nedate', models.CharField(max_length=100)),
                ('ntime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=100)),
                ('pemail', models.EmailField(max_length=254)),
                ('descr', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('utype', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=150)),
                ('edesc', models.CharField(max_length=1000)),
                ('edoclink', models.URLField(max_length=300)),
                ('einame', models.CharField(max_length=150)),
                ('eidesc', models.CharField(max_length=1000)),
                ('eilink', models.URLField(max_length=300)),
                ('edate', models.CharField(max_length=100)),
                ('etime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=100)),
                ('pemail', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('utype', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
